// Created by cgo -godefs - DO NOT EDIT
// cgo.exe -godefs ctype_1.go

package internal

type AccountInfo struct {
	AccountNo          [11]byte
	AccountName        [40]byte
	AccountProductCode [3]byte
	AmnTabCode         [4]byte
	ExpirationDate     [8]byte
	Granted            byte
	Filler             [189]byte
}
type LoginInfo struct {
	Date         [14]byte
	ServerName   [15]byte
	UserID       [8]byte
	AccountCount [3]byte
	Accountlist  [999]AccountInfo
}
type LoginBlock struct {
	TrIdNo    int32
	Pad_cgo_0 [4]byte
	LoginInfo *LoginInfo
}

type MsgHeader struct {
	MsgCode [5]byte
	UsrMsg  [80]byte
}

type Received struct {
	BlockName  *byte
	DataString *byte
	Length     int32
	Pad_cgo_0  [4]byte
}
type OutDataBlock struct {
	TrIdNo     int32
	Pad_cgo_0  [4]byte
	DataStruct *Received
}

type Tc1101InBlock struct {
	Lang   [1]byte
	X_Lang byte
	Code   [6]byte
	X_Code byte
}
type Tc1101OutBlock struct {
	Code                 [6]byte
	X_Code               byte
	Title                [13]byte
	X_Title              byte
	MarketPrice          [7]byte
	X_MarketPrice        byte
	DiffSign             [1]byte
	X_DiffSign           byte
	Diff                 [6]byte
	X_Diff               byte
	DiffRate             [5]byte
	X_DiffRate           byte
	OfferPrice           [7]byte
	X_OfferPrice         byte
	BidPrice             [7]byte
	X_BidPrice           byte
	Volume               [9]byte
	X_Volume             byte
	TrVolRate            [6]byte
	X_TrVolRate          byte
	FloatRate            [5]byte
	X_FloatRate          byte
	TrAmount             [9]byte
	X_TrAmount           byte
	UpLmtPrice           [7]byte
	X_UpLmtPrice         byte
	High                 [7]byte
	X_High               byte
	Open                 [7]byte
	X_Open               byte
	VsOpenSign           [1]byte
	X_VsOpenSign         byte
	VsOpenDiff           [6]byte
	X_VsOpenDiff         byte
	Low                  [7]byte
	X_Low                byte
	LowLmtPrice          [7]byte
	X_LowLmtPrice        byte
	Time                 [8]byte
	X_Time               byte
	OfferPrice1          [7]byte
	X_OfferPrice1        byte
	OfferPrice2          [7]byte
	X_OfferPrice2        byte
	OfferPrice3          [7]byte
	X_OfferPrice3        byte
	OfferPrice4          [7]byte
	X_OfferPrice4        byte
	OfferPrice5          [7]byte
	X_OfferPrice5        byte
	OfferPrice6          [7]byte
	X_OfferPrice6        byte
	OfferPrice7          [7]byte
	X_OfferPrice7        byte
	OfferPrice8          [7]byte
	X_OfferPrice8        byte
	OfferPrice9          [7]byte
	X_OfferPrice9        byte
	OfferPrice10         [7]byte
	X_OfferPrice10       byte
	BidPrice1            [7]byte
	X_BidPrice1          byte
	BidPrice2            [7]byte
	X_BidPrice2          byte
	BidPrice3            [7]byte
	X_BidPrice3          byte
	BidPrice4            [7]byte
	X_BidPrice4          byte
	BidPrice5            [7]byte
	X_BidPrice5          byte
	BidPrice6            [7]byte
	X_BidPrice6          byte
	BidPrice7            [7]byte
	X_BidPrice7          byte
	BidPrice8            [7]byte
	X_BidPrice8          byte
	BidPrice9            [7]byte
	X_BidPrice9          byte
	BidPrice10           [7]byte
	X_BidPrice10         byte
	OfferVolume1         [9]byte
	X_OfferVolume1       byte
	OfferVolume2         [9]byte
	X_OfferVolume2       byte
	OfferVolume3         [9]byte
	X_OfferVolume3       byte
	OfferVolume4         [9]byte
	X_OfferVolume4       byte
	OfferVolume5         [9]byte
	X_OfferVolume5       byte
	OfferVolume6         [9]byte
	X_OfferVolume6       byte
	OfferVolume7         [9]byte
	X_OfferVolume7       byte
	OfferVolume8         [9]byte
	X_OfferVolume8       byte
	OfferVolume9         [9]byte
	X_OfferVolume9       byte
	OfferVolume10        [9]byte
	X_OfferVolume10      byte
	BidVolume1           [9]byte
	X_BidVolume1         byte
	BidVolume2           [9]byte
	X_BidVolume2         byte
	BidVolume3           [9]byte
	X_BidVolume3         byte
	BidVolume4           [9]byte
	X_BidVolume4         byte
	BidVolume5           [9]byte
	X_BidVolume5         byte
	BidVolume6           [9]byte
	X_BidVolume6         byte
	BidVolume7           [9]byte
	X_BidVolume7         byte
	BidVolume8           [9]byte
	X_BidVolume8         byte
	BidVolume9           [9]byte
	X_BidVolume9         byte
	BidVolume10          [9]byte
	X_BidVolume10        byte
	OfferVolTot          [9]byte
	X_OfferVolTot        byte
	BidVolTot            [9]byte
	X_BidVolTot          byte
	OfferVolAfterHour    [9]byte
	X_OfferVolAfterHour  byte
	BidVolAfterHour      [9]byte
	X_BidVolAfterHour    byte
	PivotUp2             [7]byte
	X_PivotUp2           byte
	PivotUp1             [7]byte
	X_PivotUp1           byte
	PivotPrice           [7]byte
	X_PivotPrice         byte
	PivotDown1           [7]byte
	X_PivotDown1         byte
	PivotDown2           [7]byte
	X_PivotDown2         byte
	Market               [6]byte
	X_Market             byte
	Sector               [18]byte
	X_Sector             byte
	CapSize              [6]byte
	X_CapSize            byte
	SettleMonth          [16]byte
	X_SettleMonth        byte
	MarketAction1        [16]byte
	X_MarketAction1      byte
	MarketAction2        [16]byte
	X_MarketAction2      byte
	MarketAction3        [16]byte
	X_MarketAction3      byte
	MarketAction4        [16]byte
	X_MarketAction4      byte
	MarketAction5        [16]byte
	X_MarketAction5      byte
	MarketAction6        [16]byte
	X_MarketAction6      byte
	CircuitBreaker       [6]byte
	X_CircuitBreaker     byte
	NominalPrice         [7]byte
	X_NominalPrice       byte
	PrevPriceTitle       [12]byte
	X_PrevPriceTitle     byte
	PrevPrice            [7]byte
	X_PrevPrice          byte
	CollateralValue      [7]byte
	X_SubstituteValue    byte
	PublicOfferPrice     [7]byte
	X_PublicOfferPrice   byte
	High5Day             [7]byte
	X_High5Day           byte
	Low5Day              [7]byte
	X_Low5Day            byte
	High20Day            [7]byte
	X_High20Day          byte
	Low20Day             [7]byte
	X_Low20Day           byte
	High1Year            [7]byte
	X_High1Year          byte
	High1YearDate        [4]byte
	X_High1YearDate      byte
	Low1Year             [7]byte
	X_Low1Year           byte
	Low1YearDate         [4]byte
	X_Low1YearDate       byte
	FloatVolume          [8]byte
	X_FloatVolume        byte
	ListVolBy1000        [12]byte
	X_ListVolBy1000      byte
	MarketCapital        [9]byte
	X_MarketCapital      byte
	TraderInfoTime       [5]byte
	X_TraderInfoTime     byte
	Seller1              [6]byte
	X_Seller1            byte
	Buyer1               [6]byte
	X_Buyer1             byte
	Seller1Volume        [9]byte
	X_Seller1Volume      byte
	Buyer1Volume         [9]byte
	X_Buyer1Volume       byte
	Seller2              [6]byte
	X_Seller2            byte
	Buyer2               [6]byte
	X_Buyer2             byte
	Seller2Volume        [9]byte
	X_Seller2Volume      byte
	Buyer2Volume         [9]byte
	X_Buyer2Volume       byte
	Seller3              [6]byte
	X_Seller3            byte
	Buyer3               [6]byte
	X_Buyer3             byte
	Seller3Volume        [9]byte
	X_Seller3Volume      byte
	Buyer3Volume         [9]byte
	X_Buyer3Volume       byte
	Seller4              [6]byte
	X_Seller4            byte
	Buyer4               [6]byte
	X_Buyer4             byte
	Seller4Volume        [9]byte
	X_Seller4Volume      byte
	Buyer4Volume         [9]byte
	X_Buyer4Volume       byte
	Seller5              [6]byte
	X_Seller5            byte
	Buyer5               [6]byte
	X_Buyer5             byte
	Seller5Volume        [9]byte
	X_Seller5Volume      byte
	Buyer5Volume         [9]byte
	X_Buyer5Volume       byte
	ForeignSellVolume    [9]byte
	X_ForeignSellVolume  byte
	ForeignBuyVolume     [9]byte
	X_ForeignBuyVolume   byte
	ForeignTime          [6]byte
	X_ForeignTime        byte
	ForeignHoldingRate   [5]byte
	X_ForeignHoldingRate byte
	SettleDate           [4]byte
	X_SettleDate         byte
	DebtPercent          [5]byte
	X_DebtPercent        byte
	RightsIssueDate      [4]byte
	X_RightsIssueDate    byte
	BonusIssueDate       [4]byte
	X_BonusIssueDate     byte
	RightsIssueRate      [5]byte
	X_RightsIssueRate    byte
	BonusIssueRate       [5]byte
	X_BonusIssueRate     byte
	ForeignFloatVol      [10]byte
	X_ForeignFloatVol    byte
	TreasuryStock        [1]byte
	X_TreasuryStock      byte
	IpoDate              [8]byte
	X_IpoDate            byte
	MajorHoldRate        [5]byte
	X_MajorHoldRate      byte
	MajorHoldInfoDate    [6]byte
	X_MajorHoldInfoDate  byte
	FourLeafClover       [1]byte
	X_FourLeafClover     byte
	MarginRate           [1]byte
	X_MarginRate         byte
	Capital              [9]byte
	X_Capital            byte
	SellTotalSum         [9]byte
	X_SellTotalSum       byte
	BuyTotalSum          [9]byte
	X_BuyTotalSum        byte
	Title2               [21]byte
	X_Title2             byte
	BackdoorListing      [1]byte
	X_BackdoorListing    byte
	FloatRate2           [6]byte
	X_FloatRate2         byte
	Market2              [6]byte
	X_Market2            byte
	DebtTrDate           [4]byte
	X_DebtTrDate         byte
	DebtTrPercent        [5]byte
	X_DebtTrPercent      byte
	PER                  [5]byte
	X_PER                byte
	DebtLimit            [1]byte
	X_DebtLimit          byte
	WeightAvgPrice       [7]byte
	X_WeightAvgPrice     byte
	ListedVolume         [12]byte
	X_ListedVolume       byte
	AddListing           [12]byte
	X_AddListing         byte
	Comment              [100]byte
	X_Comment            byte
	PrevVolume           [9]byte
	X_PrevVolume         byte
	VsPrevSign           [1]byte
	X_VsPrevSign         byte
	VsPrevDiff           [6]byte
	X_VsPrevDiff         byte
	High1Year2           [7]byte
	X_High1Year2         byte
	High1YearDate2       [4]byte
	X_High1YearDate2     byte
	Low1Year2            [7]byte
	X_Low1Year2          byte
	Low1YearDate2        [4]byte
	X_Low1YearDate2      byte
	ForeignHoldQty       [15]byte
	X_ForeignHoldQty     byte
	ForeignLmtPercent    [5]byte
	X_ForeignLmtPercent  byte
	TrUnitVolume         [5]byte
	X_TrUnitVolume       byte
	DarkPoolOfferBid     [1]byte
	X_DarkPoolOfferBid   byte
	DarkPoolExist        [1]byte
	X_DarkPoolExist      byte
}
type Tc1101OutBlock2 struct {
	Time          [8]byte
	X_Time        byte
	MarketPrice   [7]byte
	X_MarketPrice byte
	DiffSign      [1]byte
	X_DiffSign    byte
	Diff          [6]byte
	X_Diff        byte
	OfferPrice    [7]byte
	X_OfferPrice  byte
	BidPrice      [7]byte
	X_BidPrice    byte
	DiffVolume    [8]byte
	X_DiffVolume  byte
	Volume        [9]byte
	X_Volume      byte
}
type Tc1101OutBlock3 struct {
	SyncOfferBid       [1]byte
	X_SyncOfferBid     byte
	EstmPrice          [7]byte
	X_EstmPrice        byte
	EstmSign           [1]byte
	X_EstmSign         byte
	EstmDiff           [6]byte
	X_EstmDiff         byte
	EstmDiffRate       [5]byte
	X_EstmDiffRate     byte
	EstmVolume         [9]byte
	X_EstmVol          byte
	ECN_InfoExist      [1]byte
	X_ECN_InfoExist    byte
	ECN_PrevPrice      [9]byte
	X_ECN_PrevPrice    byte
	ECN_DiffSign       [1]byte
	X_ECN_DiffSign     byte
	ECN_Diff           [9]byte
	X_ECN_Diff         byte
	ECN_DiffRate       [5]byte
	X_ECN_DiffRate     byte
	ECN_Volume         [10]byte
	X_ECN_Volume       byte
	VsECN_EstmSign     [1]byte
	X_VsECN_EstmSign   byte
	VsECN_EstmDiff     [6]byte
	X_VsECN_EstmDiff   byte
	VsECN_EstmDiffRate [5]byte
	X_ECN_EstmDiffRate byte
}

type Tc1151InBlock struct {
	Lang   [1]byte
	X_Lang byte
	Code   [6]byte
	X_Code byte
}
type Tc1151OutBlock struct {
	Code                 [6]byte
	X_Code               byte
	Title                [13]byte
	X_Title              byte
	MarketPrice          [7]byte
	X_MarketPrice        byte
	DiffSign             [1]byte
	X_DiffSign           byte
	Diff                 [6]byte
	X_Diff               byte
	DiffRate             [5]byte
	X_DiffRate           byte
	OfferPrice           [7]byte
	X_OfferPrice         byte
	BidPrice             [7]byte
	X_BidPrice           byte
	Volume               [9]byte
	X_Volume             byte
	TrVolRate            [6]byte
	X_TrVolRate          byte
	FloatVolRate         [5]byte
	X_FloatVolRate       byte
	TrAmount             [9]byte
	X_TrAmount           byte
	UpLmtPrice           [7]byte
	X_UpLmtPrice         byte
	High                 [7]byte
	X_High               byte
	Open                 [7]byte
	X_Open               byte
	VsOpenSign           [1]byte
	X_VsOpenSign         byte
	VsOpenDiff           [6]byte
	X_VsOpenDiff         byte
	Low                  [7]byte
	X_Low                byte
	LowLmtPrice          [7]byte
	X_LowLmtPrice        byte
	Time                 [8]byte
	X_Time               byte
	OfferPrice1          [7]byte
	X_OfferPrice1        byte
	OfferPrice2          [7]byte
	X_OfferPrice2        byte
	OfferPrice3          [7]byte
	X_OfferPrice3        byte
	OfferPrice4          [7]byte
	X_OfferPrice4        byte
	OfferPrice5          [7]byte
	X_OfferPrice5        byte
	OfferPrice6          [7]byte
	X_OfferPrice6        byte
	OfferPrice7          [7]byte
	X_OfferPrice7        byte
	OfferPrice8          [7]byte
	X_OfferPrice8        byte
	OfferPrice9          [7]byte
	X_OfferPrice9        byte
	OfferPrice10         [7]byte
	X_OfferPrice10       byte
	BidPrice1            [7]byte
	X_BidPrice1          byte
	BidPrice2            [7]byte
	X_BidPrice2          byte
	BidPrice3            [7]byte
	X_BidPrice3          byte
	BidPrice4            [7]byte
	X_BidPrice4          byte
	BidPrice5            [7]byte
	X_BidPrice5          byte
	BidPrice6            [7]byte
	X_BidPrice6          byte
	BidPrice7            [7]byte
	X_BidPrice7          byte
	BidPrice8            [7]byte
	X_BidPrice8          byte
	BidPrice9            [7]byte
	X_BidPrice9          byte
	BidPrice10           [7]byte
	X_BidPrice10         byte
	OfferVolume1         [9]byte
	X_OfferVolume1       byte
	OfferVolume2         [9]byte
	X_OfferVolume2       byte
	OfferVolume3         [9]byte
	X_OfferVolume3       byte
	OfferVolume4         [9]byte
	X_OfferVolume4       byte
	OfferVolume5         [9]byte
	X_OfferVolume5       byte
	OfferVolume6         [9]byte
	X_OfferVolume6       byte
	OfferVolume7         [9]byte
	X_OfferVolume7       byte
	OfferVolume8         [9]byte
	X_OfferVolume8       byte
	OfferVolume9         [9]byte
	X_OfferVolume9       byte
	OfferVolume10        [9]byte
	X_OfferVolume10      byte
	BidVolume1           [9]byte
	X_BidVolume1         byte
	BidVolume2           [9]byte
	X_BidVolume2         byte
	BidVolume3           [9]byte
	X_BidVolume3         byte
	BidVolume4           [9]byte
	X_BidVolume4         byte
	BidVolume5           [9]byte
	X_BidVolume5         byte
	BidVolume6           [9]byte
	X_BidVolume6         byte
	BidVolume7           [9]byte
	X_BidVolume7         byte
	BidVolume8           [9]byte
	X_BidVolume8         byte
	BidVolume9           [9]byte
	X_BidVolume9         byte
	BidVolume10          [9]byte
	X_BidVolume10        byte
	OfferVolTot          [9]byte
	X_OfferVolTot        byte
	BidVolTot            [9]byte
	X_BidVolTot          byte
	OfferVolAfterHour    [9]byte
	X_OfferVolAfterHour  byte
	BidVolAfterHour      [9]byte
	X_BidVolAfterHour    byte
	PivotUp2             [7]byte
	X_PivotUp2           byte
	PivotUp1             [7]byte
	X_PivotUp1           byte
	PivotPrice           [7]byte
	X_PivotPrice         byte
	PivotDown1           [7]byte
	X_PivotDown1         byte
	PivotDown2           [7]byte
	X_PivotDown2         byte
	Market               [6]byte
	X_Market             byte
	Sector               [18]byte
	X_Sector             byte
	CapSize              [6]byte
	X_CapSize            byte
	SettleMonth          [16]byte
	X_SettleMonth        byte
	MarketAction1        [16]byte
	X_MarketAction1      byte
	MarketAction2        [16]byte
	X_MarketAction2      byte
	MarketAction3        [16]byte
	X_MarketAction3      byte
	MarketAction4        [16]byte
	X_MarketAction4      byte
	MarketAction5        [16]byte
	X_MarketAction5      byte
	MarketAction6        [16]byte
	X_MarketAction6      byte
	CircuitBreaker       [6]byte
	X_CircuitBreaker     byte
	NominalPrice         [7]byte
	X_NominalPrice       byte
	PrevPriceTitle       [12]byte
	X_PrevPriceTitle     byte
	PrevPrice            [7]byte
	X_PrevPrice          byte
	MortgageValue        [7]byte
	X_MortgageValue      byte
	PublicOfferPrice     [7]byte
	X_PublicOfferPrice   byte
	High5Day             [7]byte
	X_High5Day           byte
	Low5Day              [7]byte
	X_Low5Day            byte
	High20Day            [7]byte
	X_High20Day          byte
	Low20Day             [7]byte
	X_Low20Day           byte
	High1Year            [7]byte
	X_High1Year          byte
	High1YearDate        [4]byte
	X_High1YearDate      byte
	Low1Year             [7]byte
	X_Low1Year           byte
	Low1YearDate         [4]byte
	X_Low1YearDate       byte
	FloatVolume          [8]byte
	X_FloatVolume        byte
	ListVolBy1000        [12]byte
	X_ListVolBy1000      byte
	MarketCapital        [9]byte
	X_MarketCapital      byte
	TraderInfoTime       [5]byte
	X_TraderInfoTime     byte
	Seller1              [6]byte
	X_Seller1            byte
	Buyer1               [6]byte
	X_Buyer1             byte
	Seller1Volume        [9]byte
	X_Seller1Volume      byte
	Buyer1Volume         [9]byte
	X_Buyer1Volume       byte
	Seller2              [6]byte
	X_Seller2            byte
	Buyer2               [6]byte
	X_Buyer2             byte
	Seller2Volume        [9]byte
	X_Seller2Volume      byte
	Buyer2Volume         [9]byte
	X_Buyer2Volume       byte
	Seller3              [6]byte
	X_Seller3            byte
	Buyer3               [6]byte
	X_Buyer3             byte
	Seller3Volume        [9]byte
	X_Seller3Volume      byte
	Buyer3Volume         [9]byte
	X_Buyer3Volume       byte
	Seller4              [6]byte
	X_Seller4            byte
	Buyer4               [6]byte
	X_Buyer4             byte
	Seller4Volume        [9]byte
	X_Seller4Volume      byte
	Buyer4Volume         [9]byte
	X_Buyer4Volume       byte
	Seller5              [6]byte
	X_Seller5            byte
	Buyer5               [6]byte
	X_Buyer5             byte
	Seller5Volume        [9]byte
	X_Seller5Volume      byte
	Buyer5Volume         [9]byte
	X_Buyer5Volume       byte
	ForeignSellVolume    [9]byte
	X_ForeignSellVolume  byte
	ForeignBuyVolume     [9]byte
	X_ForeignBuyVolume   byte
	ForeignTime          [6]byte
	X_ForeignTime        byte
	ForeignHoldingRate   [5]byte
	X_ForeignHoldingRate byte
	SettleDate           [4]byte
	X_SettleDate         byte
	DebtPercent          [5]byte
	X_DebtPercent        byte
	RightsIssueDate      [4]byte
	X_RightsIssueDate    byte
	BonusIssueDate       [4]byte
	X_BonusIssueDate     byte
	RightsIssueRate      [5]byte
	X_RightsIssueRate    byte
	BonusIssueRate       [5]byte
	X_BonusIssueRate     byte
	IpoDate              [8]byte
	X_IpoDate            byte
	ListedVolume         [12]byte
	X_ListedVolume       byte
	SellTotalSum         [9]byte
	X_SellTotalSum       byte
	BuyTotalSum          [9]byte
	X_BuyTotalSum        byte
}
type Tc1151OutBlock2 struct {
	Time          [8]byte
	X_Time        byte
	MarketPrice   [7]byte
	X_MarketPrice byte
	DiffSign      [1]byte
	X_DiffSign    byte
	Diff          [6]byte
	X_Diff        byte
	OfferPrice    [7]byte
	X_OfferPrice  byte
	BidPrice      [7]byte
	X_BidPrice    byte
	DiffVolume    [8]byte
	X_DiffVolume  byte
	Volume        [9]byte
	X_Volume      byte
}
type Tc1151OutBlock3 struct {
	SyncOfferBid   [1]byte
	X_SyncOfferBid byte
	EstmPrice      [7]byte
	X_EstmPrice    byte
	EstmSign       [1]byte
	X_EstmSign     byte
	EstmDiff       [6]byte
	X_EstmDiff     byte
	EstmDiffRate   [5]byte
	X_EstmDiffRate byte
	EstmVolume     [9]byte
	X_EstmVolume   byte
}
type Tc1151OutBlock4 struct {
	ETF                [1]byte
	X_ETF              byte
	NAV                [9]byte
	X_NAV              byte
	DiffSign           [1]byte
	X_DiffSign         byte
	Diff               [9]byte
	X_Diff             byte
	PrevNAV            [9]byte
	X_PrevNAV          byte
	DivergeRate        [9]byte
	X_DivergeRate      byte
	DivergeSign        [1]byte
	X_DivergeSign      byte
	DividendPerCU      [18]byte
	X_DividendPerCU    byte
	ConstituentNo      [4]byte
	X_ConstituentNo    byte
	NAVBy100Million    [7]byte
	X_NAVBy100Million  byte
	TrackingErrRate    [9]byte
	X_TrackingErrRate  byte
	LP_OfferVolume1    [9]byte
	X_LP_OfferVolume1  byte
	LP_OfferVolume2    [9]byte
	X_LP_OfferVolume2  byte
	LP_OfferVolume3    [9]byte
	X_LP_OfferVolume3  byte
	LP_OfferVolume4    [9]byte
	X_LP_OfferVolume4  byte
	LP_OfferVolume5    [9]byte
	X_LP_OfferVolume5  byte
	LP_OfferVolume6    [9]byte
	X_LP_OfferVolume6  byte
	LP_OfferVolume7    [9]byte
	X_LP_OfferVolume7  byte
	LP_OfferVolume8    [9]byte
	X_LP_OfferVolume8  byte
	LP_OfferVolume9    [9]byte
	X_LP_OfferVolume9  byte
	LP_OfferVolume10   [9]byte
	X_LP_OfferVolume10 byte
	LP_BidVolume1      [9]byte
	X_LP_BidVolume1    byte
	LP_BidVolume2      [9]byte
	X_LP_BidVolume2    byte
	LP_BidVolume3      [9]byte
	X_LP_BidVolume3    byte
	LP_BidVolume4      [9]byte
	X_LP_BidVolume4    byte
	LP_BidVolume5      [9]byte
	X_LP_BidVolume5    byte
	LP_BidVolume6      [9]byte
	X_LP_BidVolume6    byte
	LP_BidVolume7      [9]byte
	X_LP_BidVolume7    byte
	LP_BidVolume8      [9]byte
	X_LP_BidVolume8    byte
	LP_BidVolume9      [9]byte
	X_LP_BidVolume9    byte
	LP_BidVolume10     [9]byte
	X_LP_BidVolume10   byte
	TrackingMethod     [8]byte
	X_TrackingMethod   byte
	ETF_Type           [6]byte
	X_ETF_Type         byte
}
type Tc1151OutBlock5 struct {
	SectorCode           [2]byte
	X_SectorCode         byte
	IndexCode            [4]byte
	X_IndexCode          byte
	IndexName            [20]byte
	X_IndexName          byte
	KP200Index           [8]byte
	X_KP200Index         byte
	KP200Sign            [1]byte
	X_KP200Sign          byte
	KP200Diff            [8]byte
	X_KP200Diff          byte
	BondIndex            [10]byte
	X_BondIndex          byte
	BondSign             [1]byte
	X_BondSign           byte
	BondDiff             [10]byte
	X_BondDiff           byte
	ForeignIndexSymbol   [12]byte
	X_ForeignIndexSymbol byte
	EtcSectorCode        [3]byte
	X_EtcSectorCode      byte
	BondIndexCode        [6]byte
	X_BondIndexCode      byte
	BondDetailCode       [1]byte
	X_BondDetailCode     byte
}

type TCodeInBlock struct {
	Code [6]byte
}

type TSectorCodeInBlock struct {
	SectorCode   [2]byte
	X_SectorCode byte
}

type Th1k3OutBlock struct {
	Skip             [3]byte
	Code             [6]byte
	Time             [8]byte
	OfferPrice1      [7]byte
	BidPrice1        [7]byte
	OfferVolume1     [9]byte
	BidVolume1       [9]byte
	OfferPrice2      [7]byte
	BidPrice2        [7]byte
	OfferVolume2     [9]byte
	BidVolume2       [9]byte
	OfferPrice3      [7]byte
	BidPrice3        [7]byte
	OfferVolume3     [9]byte
	BidVolume3       [9]byte
	OfferPrice4      [7]byte
	BidPrice4        [7]byte
	OfferVolume4     [9]byte
	BidVolume4       [9]byte
	OfferPrice5      [7]byte
	BidPrice5        [7]byte
	OfferVolume5     [9]byte
	BidVolume5       [9]byte
	OfferVolumeTotal [9]byte
	BidVolumeTotal   [9]byte
	OfferPrice6      [7]byte
	BidPrice6        [7]byte
	OfferVolume6     [9]byte
	BidVolume6       [9]byte
	OfferPrice7      [7]byte
	BidPrice7        [7]byte
	OfferVolume7     [9]byte
	BidVolume7       [9]byte
	OfferPrice8      [7]byte
	BidPrice8        [7]byte
	OfferVolume8     [9]byte
	BidVolume8       [9]byte
	OfferPrice9      [7]byte
	BidPrice9        [7]byte
	OfferVolume9     [9]byte
	BidVolume9       [9]byte
	OfferPrice10     [7]byte
	BidPrice10       [7]byte
	OfferVolume10    [9]byte
	BidVolume10      [9]byte
	Volume           [9]byte
}

type Th2k4OutBlock struct {
	Skip        [3]byte
	Code        [6]byte
	Time        [8]byte
	OfferVolume [9]byte
	BidVolume   [9]byte
}

type Th3k5OutBlock struct {
	Skip         [3]byte
	Code         [6]byte
	Time         [8]byte
	SyncOfferBid [1]byte
	EstmPrice    [7]byte
	EstmDiffSign [1]byte
	EstmDiff     [6]byte
	EstmDiffRate [5]byte
	EstmVolume   [9]byte
	OfferPrice   [7]byte
	BidPrice     [7]byte
	OfferVolume  [9]byte
	BidVolume    [9]byte
}

type Tj8OutBlock struct {
	Skip             [3]byte
	Code             [6]byte
	X_Code           byte
	Time             [8]byte
	X_Time           byte
	DiffSign         [1]byte
	X_DiffSign       byte
	Diff             [6]byte
	X_Diff           byte
	MarketPrice      [7]byte
	X_MarketPrice    byte
	DiffRate         [5]byte
	X_DiffRate       byte
	High             [7]byte
	X_High           byte
	Low              [7]byte
	X_Low            byte
	OfferPrice       [7]byte
	X_OfferPrice     byte
	BidPrice         [7]byte
	X_BidPrice       byte
	Volume           [9]byte
	X_Volume         byte
	VsPrevVolRate    [6]byte
	X_VsPrevVolRate  byte
	DiffVolume       [8]byte
	X_DiffVolume     byte
	TrAmount         [9]byte
	X_TrAmount       byte
	Open             [7]byte
	X_Open           byte
	WeightAvgPrice   [7]byte
	X_WeightAvgPrice byte
	Market           [1]byte
	X_Market         byte
}
type Tk8OutBlock struct {
	Skip             [3]byte
	Code             [6]byte
	X_Code           byte
	Time             [8]byte
	X_Time           byte
	MarketPrice      [7]byte
	X_MarketPrice    byte
	DiffSign         [1]byte
	X_DiffSign       byte
	Diff             [6]byte
	X_Diff           byte
	DiffRate         [5]byte
	X_DiffRate       byte
	High             [7]byte
	X_High           byte
	Low              [7]byte
	X_Low            byte
	OfferPrice       [7]byte
	X_OfferPrice     byte
	BidPrice         [7]byte
	X_BidPrice       byte
	Volume           [9]byte
	X_Volume         byte
	VsPrevVolRate    [6]byte
	X_VsPrevVolRate  byte
	DiffVolume       [8]byte
	X_DiffVolume     byte
	TrAmount         [9]byte
	X_TrAmount       byte
	Open             [7]byte
	X_Open           byte
	WeightAvgPrice   [7]byte
	X_WeightAvgPrice byte
	Market           [1]byte
	X_Market         byte
}

type Tj0j1OutBlock struct {
	Skip            [3]byte
	Code            [6]byte
	X_Code          byte
	Time            [8]byte
	X_Time          byte
	DiffSign        [1]byte
	X_DiffSign      byte
	Diff            [9]byte
	X_Diff          byte
	Current         [9]byte
	X_NAV_Current   byte
	Open            [9]byte
	X_NAV_Open      byte
	High            [9]byte
	X_NAV_High      byte
	Low             [9]byte
	X_NAV_Low       byte
	TrackErrSign    [1]byte
	X_TrackingSign  byte
	TrackingError   [9]byte
	X_TrackingError byte
	DivergeSign     [1]byte
	X_DivergeSign   byte
	DivergeRate     [9]byte
	X_DivergeRate   byte
}

type Tu1k1OutBlock struct {
	Skip         [3]byte
	SectorCode   [2]byte
	X_SectorCode byte
	Time         [8]byte
	X_Time       byte
	IndexValue   [8]byte
	X_IndexValue byte
	DiffSign     [1]byte
	X_DiffSign   byte
	Diff         [8]byte
	X_Diff       byte
	Volume       [8]byte
	X_Volume     byte
	TrAmount     [8]byte
	X_TrAmount   byte
	Open         [8]byte
	X_Open       byte
	High         [8]byte
	X_High       byte
	HighTime     [8]byte
	X_HighTime   byte
	Low          [8]byte
	X_Low        byte
	LowTime      [8]byte
	X_LowTime    byte
	DiffRate     [5]byte
	X_DiffRate   byte
	TrVolRate    [5]byte
	X_TrVolRate  byte
}

type Tc8101InBlock struct {
	Pswd_noz8             [44]byte
	X_pswd_noz8           byte
	Issue_codez6          [6]byte
	X_issue_codez6        byte
	Order_qtyz12          [12]byte
	X_order_qtyz12        byte
	Order_unit_pricez10   [10]byte
	X_order_unit_pricez10 byte
	Trade_typez2          [2]byte
	X_trade_typez2        byte
	Shsll_pos_flagz1      [1]byte
	X_shsll_pos_flagz1    byte
	Trad_pswd_no_1z8      [44]byte
	X_trad_pswd_no_1z8    byte
	Trad_pswd_no_2z8      [44]byte
	X_trad_pswd_no_2z8    byte
}
type Tc8101OutBlock struct {
	Noz10                 [10]byte
	X_order_noz10         byte
	Qtyz12                [12]byte
	X_order_qtyz12        byte
	Unit_pricez10         [10]byte
	X_order_unit_pricez10 byte
}

type Tc8102InBlock struct {
	Pswd_noz8             [44]byte
	X_pswd_noz8           byte
	Issue_codez6          [6]byte
	X_issue_codez6        byte
	Order_qtyz12          [12]byte
	X_order_qtyz12        byte
	Order_unit_pricez10   [10]byte
	X_order_unit_pricez10 byte
	Trade_typez2          [2]byte
	X_trade_typez2        byte
	Trad_pswd_no_1z8      [44]byte
	X_trad_pswd_no_1z8    byte
	Trad_pswd_no_2z8      [44]byte
	X_trad_pswd_no_2z8    byte
}
type Tc8102OutBlock struct {
	Noz10                 [10]byte
	X_order_noz10         byte
	Qtyz12                [12]byte
	X_order_qtyz12        byte
	Unit_pricez10         [10]byte
	X_order_unit_pricez10 byte
}

type Tc8103InBlock struct {
	Pswd_noz8           [44]byte
	X_pswd_noz8         byte
	Issue_codez6        [6]byte
	X_issue_codez6      byte
	Crctn_qtyz12        [12]byte
	X_crctn_qtyz12      byte
	Crctn_pricez10      [10]byte
	X_crctn_pricez10    byte
	Orgnl_order_noz10   [10]byte
	X_orgnl_order_noz10 byte
	All_part_typez1     [1]byte
	X_all_part_typez1   byte
	Trad_pswd_no_1z8    [44]byte
	X_trad_pswd_no_1z8  byte
	Trad_pswd_no_2z8    [44]byte
	X_trad_pswd_no_2z8  byte
}
type Tc8103OutBlock struct {
	Orgnl_order_noz10   [10]byte
	X_orgnl_order_noz10 byte
	Order_noz10         [10]byte
	X_order_noz10       byte
	Mom_order_noz10     [10]byte
	X_mom_order_noz10   byte
	Issue_codez6        [6]byte
	X_issue_codez6      byte
	Crctn_qtyz12        [12]byte
	X_crctn_qtyz12      byte
	Crctn_pricez10      [10]byte
	X_crctn_pricez10    byte
}

type Tc8104InBlock struct {
	Pswd_noz8           [44]byte
	X_pswd_noz8         byte
	Issue_codez6        [6]byte
	X_issue_codez6      byte
	Canc_qtyz12         [12]byte
	X_canc_qtyz12       byte
	Orgnl_order_noz10   [10]byte
	X_orgnl_order_noz10 byte
	All_part_typez1     [1]byte
	X_all_part_typez1   byte
	Trad_pswd_no_1z8    [44]byte
	X_trad_pswd_no_1z8  byte
	Trad_pswd_no_2z8    [44]byte
	X_trad_pswd_no_2z8  byte
}
type Tc8104OutBlock struct {
	Orgnl_order_noz10   [10]byte
	X_orgnl_order_noz10 byte
	Order_noz10         [10]byte
	X_order_noz10       byte
	Mom_order_noz10     [10]byte
	X_mom_order_noz10   byte
	Issue_codez6        [6]byte
	X_issue_codez6      byte
	Canc_qtyz12         [12]byte
	X_canc_qtyz12       byte
}

type Tc8201InBlock struct {
	Pswd_noz44     [44]byte
	X_pswd_noz44   byte
	Bnc_bse_cdz1   [1]byte
	X_bnc_bse_cdz1 byte
}
type Tc8201OutBlock struct {
	Dpsit_amtz16         [16]byte
	X_dpsit_amtz16       byte
	Mrgn_amtz16          [16]byte
	X_mrgn_amtz16        byte
	Mgint_npaid_amtz16   [16]byte
	X_mgint_npaid_amtz16 byte
	Chgm_pos_amtz16      [16]byte
	X_chgm_pos_amtz16    byte
	Cash_mrgn_amtz16     [16]byte
	X_cash_mrgn_amtz16   byte
	Subst_mgamt_amtz16   [16]byte
	X_subst_mgamt_amtz16 byte
	Coltr_ratez6         [6]byte
	X_coltr_ratez6       byte
	Rcble_amtz16         [16]byte
	X_rcble_amtz16       byte
	Order_pos_csamtz16   [16]byte
	X_order_pos_csamtz16 byte
	Ecn_pos_csamtz16     [16]byte
	X_ecn_pos_csamtz16   byte
	Nordm_loan_amtz16    [16]byte
	X_nordm_loan_amtz16  byte
	Etc_lend_amtz16      [16]byte
	X_etc_lend_amtz16    byte
	Subst_amtz16         [16]byte
	X_subst_amtz16       byte
	Sln_sale_amtz16      [16]byte
	X_sln_sale_amtz16    byte
	Bal_buy_ttamtz16     [16]byte
	X_bal_buy_ttamtz16   byte
	Bal_ass_ttamtz16     [16]byte
	X_bal_ass_ttamtz16   byte
	Asset_tot_amtz16     [16]byte
	X_asset_tot_amtz16   byte
	Actvt_type10         [10]byte
	X_actvt_type10       byte
	Lend_amtz16          [16]byte
	X_lend_amtz16        byte
	Accnt_mgamt_ratez6   [6]byte
	X_accnt_mgamt_ratez6 byte
	Sl_mrgn_amtz16       [16]byte
	X_sl_mrgn_amtz16     byte
	Pos_csamt1z16        [16]byte
	X_pos_csamt1z16      byte
	Pos_csamt2z16        [16]byte
	X_pos_csamt2z16      byte
	Pos_csamt3z16        [16]byte
	X_pos_csamt3z16      byte
	Pos_csamt4z16        [16]byte
	X_pos_csamt4z16      byte
	Dpsit_amtz_d1_16     [16]byte
	X_dpsit_amtz_d1_16   byte
	Dpsit_amtz_d2_16     [16]byte
	X_dpsit_amtz_d2_16   byte
	Noticez30            [30]byte
	X_noticez30          byte
	Tot_eal_plsz18       [18]byte
	X_tot_eal_plsz18     byte
	Pft_rtz15            [15]byte
	X_pft_rtz15          byte
}
type Tc8201OutBlock1 struct {
	Issue_codez6         [6]byte
	X_issue_codez6       byte
	Issue_namez40        [40]byte
	X_issue_namez40      byte
	Bal_typez6           [6]byte
	X_bal_typez6         byte
	Loan_datez10         [10]byte
	X_loan_datez10       byte
	Bal_qtyz16           [16]byte
	X_bal_qtyz16         byte
	Unstl_qtyz16         [16]byte
	X_unstl_qtyz16       byte
	Slby_amtz16          [16]byte
	X_slby_amtz16        byte
	Prsnt_pricez16       [16]byte
	X_prsnt_pricez16     byte
	Lsnpf_amtz16         [16]byte
	X_lsnpf_amtz16       byte
	Earn_ratez9          [9]byte
	X_earn_ratez9        byte
	Mrgn_codez4          [4]byte
	X_mrgn_codez4        byte
	Jan_qtyz16           [16]byte
	X_jan_qtyz16         byte
	Expr_datez10         [10]byte
	X_expr_datez10       byte
	Ass_amtz16           [16]byte
	X_ass_amtz16         byte
	Issue_mgamt_ratez6   [6]byte
	X_issue_mgamt_ratez6 byte
	Medo_slby_amtz16     [16]byte
	X_medo_slby_amtz16   byte
	Post_lsnpf_amtz16    [16]byte
	X_post_lsnpf_amtz16  byte
}

type Ts8120InBlock struct {
	Inq_gubunz1          [1]byte
	X_inq_gubunz1        byte
	Pswd_noz8            [44]byte
	X_pswd_noz8          byte
	Group_noz4           [4]byte
	X_group_noz4         byte
	Mkt_slctz1           [1]byte
	X_mkt_slctz1         byte
	Order_datez8         [8]byte
	X_order_datez8       byte
	Issue_codez12        [12]byte
	X_issue_codez12      byte
	Comm_order_typez2    [2]byte
	X_comm_order_typez2  byte
	Conc_gubunz1         [1]byte
	X_conc_gubunz1       byte
	Inq_seq_gubunz1      [1]byte
	X_inq_seq_gubunz1    byte
	Sort_gubunz1         [1]byte
	X_sort_gubunz1       byte
	Sell_buy_typez1      [1]byte
	X_sell_buy_typez1    byte
	Mrgn_typez1          [1]byte
	X_mrgn_typez1        byte
	Accnt_admin_typez1   [1]byte
	X_accnt_admin_typez1 byte
	Order_noz10          [10]byte
	X_order_noz10        byte
	Ctsz56               [56]byte
	X_ctsz56             byte
	Trad_pswd1z8         [44]byte
	X_trad_pswd1z8       byte
	Trad_pswd2z8         [44]byte
	X_trad_pswd2z8       byte
	IsPageUp             [1]byte
	X_IsPageUp           byte
}
type Ts8120OutBlock struct {
	Emp_kor_namez20    [20]byte
	X_emp_kor_namez20  byte
	Brch_namez30       [30]byte
	X_brch_namez30     byte
	Buy_conc_qtyz14    [14]byte
	X_buy_conc_qtyz14  byte
	Buy_conc_amtz19    [19]byte
	X_buy_conc_amtz19  byte
	Sell_conc_qtyz14   [14]byte
	X_sell_conc_qtyz14 byte
	Sell_conc_amtz19   [19]byte
	X_sell_conc_amtz19 byte
}
type Ts8120OutBlock1 struct {
	Order_datez8          [8]byte
	X_order_datez8        byte
	Order_noz10           [10]byte
	X_order_noz10         byte
	Orgnl_order_noz10     [10]byte
	X_orgnl_order_noz10   byte
	Accnt_noz11           [11]byte
	X_accnt_noz11         byte
	Accnt_namez20         [20]byte
	X_accnt_namez20       byte
	Order_kindz20         [20]byte
	X_order_kindz20       byte
	Trd_gubun_noz1        [1]byte
	X_trd_gubun_noz1      byte
	Trd_gubunz20          [20]byte
	X_trd_gubunz20        byte
	Trade_type_noz1       [1]byte
	X_trade_type_noz1     byte
	Trade_type1z20        [20]byte
	X_trade_type1z20      byte
	Issue_codez12         [12]byte
	X_issue_codez12       byte
	Issue_namez40         [40]byte
	X_issue_namez40       byte
	Order_qtyz10          [10]byte
	X_order_qtyz10        byte
	Conc_qtyz10           [10]byte
	X_conc_qtyz10         byte
	Order_unit_pricez12   [12]byte
	X_order_unit_pricez12 byte
	Conc_unit_pricez12    [12]byte
	X_conc_unit_pricez12  byte
	Crctn_canc_qtyz10     [10]byte
	X_crctn_canc_qtyz10   byte
	Cfirm_qtyz10          [10]byte
	X_cfirm_qtyz10        byte
	Media_namez12         [12]byte
	X_media_namez12       byte
	Proc_emp_noz5         [5]byte
	X_proc_emp_noz5       byte
	Proc_timez8           [8]byte
	X_proc_timez8         byte
	Proc_termz8           [8]byte
	X_proc_termz8         byte
	Proc_typez12          [12]byte
	X_proc_typez12        byte
	Rejec_codez5          [5]byte
	X_rejec_codez5        byte
	Avail_qtyz10          [10]byte
	X_avail_qtyz10        byte
	Mkt_typez1            [1]byte
	X_mkt_typez1          byte
	Shsll_typez20         [20]byte
	X_shsll_typez20       byte
	Passwd_noz8           [8]byte
	X_passwd_noz8         byte
}
type Ts8120OutBlock_IN struct {
	Ctsz56       [56]byte
	X_ctsz56     byte
	Nextbutton   [1]byte
	X_nextbutton byte
}

type Tp8101InBlock struct {
	Noz8        [44]byte
	X_pswd_noz8 byte
	Gubunz1     [1]byte
	X_gubunz1   byte
}
type Tp8101OutBlock struct {
	Namez30         [30]byte
	X_accnt_namez30 byte
}
type Tp8101OutBlock1 struct {
	Gubunz1                 [1]byte
	X_gubunz1               byte
	Gubun_namez6            [6]byte
	X_gubun_namez6          byte
	Issue_codez12           [12]byte
	X_issue_codez12         byte
	Issue_namez30           [30]byte
	X_issue_namez30         byte
	Mrgn_typez10            [10]byte
	X_mrgn_typez10          byte
	Lend_datez10            [10]byte
	X_lend_datez10          byte
	Taxtn_typez10           [10]byte
	X_taxtn_typez10         byte
	Bal_qtyz12              [12]byte
	X_bal_qtyz12            byte
	Sell_rcble_qtyz12       [12]byte
	X_sell_rcble_qtyz12     byte
	Buy_rcble_qtyz12        [12]byte
	X_buy_rcble_qtyz12      byte
	Sell_psqtyz12           [12]byte
	X_sell_psqtyz12         byte
	Today_sell_rcble_qz12   [12]byte
	X_today_sell_rcble_qz12 byte
	Avrg_purch_uprc         [10]byte
	X_avrg_purch_uprc       byte
}

type Tp8105InBlock struct {
	Pwdz8            [44]byte
	X_pwdz8          byte
	Ost_dit_cdz1     [1]byte
	X_ost_dit_cdz1   byte
	Sby_dit_cdz1     [1]byte
	X_sby_dit_cdz1   byte
	Iem_gbz1         [1]byte
	X_iem_gbz1       byte
	Iem_cdz12        [12]byte
	X_iem_cdz12      byte
	Nmn_pr_tp_gbz1   [1]byte
	X_nmn_pr_tp_gbz1 byte
	Nmn_pr_tp_cdz2   [2]byte
	X_nmn_pr_tp_cdz2 byte
	Orr_prz18        [18]byte
	X_orr_prz18      byte
	Mdi_tp_cdz1      [1]byte
	X_mdi_tp_cdz1    byte
	Cfd_lon_cdz2     [2]byte
	X_cfd_lon_cdz2   byte
	Lon_dtz8         [8]byte
	X_lon_dtz8       byte
}
type Tp8105OutBlock struct {
	Dcaz18                   [18]byte
	X_dcaz18                 byte
	Nxt_dd_dcaz18            [18]byte
	X_nxt_dd_dcaz18          byte
	Nxt2_dd_dcaz18           [18]byte
	X_nxt2_dd_dcaz18         byte
	Max_pbl_amtz18           [18]byte
	X_max_pbl_amtz18         byte
	Max_pbl_qtyz18           [18]byte
	X_max_pbl_qtyz18         byte
	Rvb_orn_max_pbl_feez18   [18]byte
	X_rvb_orn_max_pbl_feez18 byte
	Csh_orr_pbl_amtz18       [18]byte
	X_csh_orr_pbl_amtz18     byte
	Csh_orr_pbl_qtyz18       [18]byte
	X_csh_orr_pbl_qtyz18     byte
	Ost_fee1z18              [18]byte
	X_ost_fee1z18            byte
	Cfd_rvb_orr_pbl_amtz18   [18]byte
	X_cfd_rvb_orr_pbl_amtz18 byte
	Cfd_rvb_orr_pbl_qtyz18   [18]byte
	X_cfd_rvb_orr_pbl_qtyz18 byte
	Cfd_max_pbl_feez18       [18]byte
	X_cfd_max_pbl_feez18     byte
	Cfd_orr_pbl_amtz18       [18]byte
	X_cfd_orr_pbl_amtz18     byte
	Cfd_orr_pbl_qtyz18       [18]byte
	X_cfd_orr_pbl_qtyz18     byte
	Ost_fee2z18              [18]byte
	X_ost_fee2z18            byte
	Sdr_xps1z18              [18]byte
	X_sdr_xps1z18            byte
	Sdr_xpsz18               [18]byte
	X_sdr_xpsz18             byte
}

type Tp8104InBlock struct {
	Pswd_noz8      [44]byte
	X_pswd_noz8    byte
	Issue_codez6   [6]byte
	X_issue_codez6 byte
	Gubunz1        [1]byte
	X_gubunz1      byte
	The_datez8     [8]byte
	X_the_datez8   byte
}
type Tp8104OutBlock struct {
	Issue_codez6   [6]byte
	X_issue_codez6 byte
	Order_qtyz12   [12]byte
	X_order_qtyz12 byte
}

type Td2OutBlock struct {
	Skip            [3]byte
	Userid          [8]byte
	Itemgb          [1]byte
	Accountno       [11]byte
	Orderno         [10]byte
	Issuecd         [15]byte
	Slbygb          [1]byte
	Concgty         [10]byte
	Concprc         [11]byte
	Conctime        [6]byte
	Ucgb            [1]byte
	Rejgb           [1]byte
	Fundcode        [3]byte
	Sin_gb          [2]byte
	Loan_date       [8]byte
	Ato_ord_tpe_chg [1]byte
	Filler          [34]byte
}

type Td3OutBlock struct {
	Skip       [3]byte
	Userid     [8]byte
	Itemgb     [1]byte
	Accountno  [11]byte
	Orderno    [10]byte
	Orgordno   [10]byte
	Ordercd    [2]byte
	Issuecd    [15]byte
	Issuename  [20]byte
	Slbygb     [1]byte
	Order_type [2]byte
	Ordergty   [10]byte
	Orderprc   [11]byte
	Procnm     [2]byte
	Commcd     [2]byte
	Order_cond [1]byte
	Fundcode   [3]byte
	Sin_gb     [2]byte
	Order_time [6]byte
	Loan_date  [8]byte
}
